/**
 * TASK 1: CREATE A ANTD TABLE TO SHOW ALL THE REFERRAL USERS
 * TASK 2: FETCH ALL USERS FROM DB VIA PRISMA SHOW THEM IN THE TABLE
 * TASK 3: MAKE REFARRAL SYSTEM WHICH MUST HAVE A REGISTRATION LINK SO THE USER CAN SHARE IT
		   ONCE ANYONE WILL CREATE AN ACCOUNT FROM THAT LINK IT WILL COUNT AS A REFERRAL USER FOR HOST USER
 */
const Referral = () => {
	return <div>refarral page</div>;
};

export default Referral;
