version: '3.1'

services:
  mysql:
    image: mariadb:10.10.2
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - ./mysql:/var/lib/mysql

    ports:
      - 3001:3306

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    restart: always
    ports:
      - 3002:80

    environment:
      - PMA_ARBITRARY=1
